// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymwbfotugdtmsoqbxsds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inltd2Jmb3R1Z2R0bXNvcWJ4c2RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MTk4MTUsImV4cCI6MjA2MzM5NTgxNX0.X_cM1p6WLOGgSp4RddJLdsELZONd9Hn5qUl9YiVSv34";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  },
  global: {
    headers: {
      'X-Client-Info': 'privy-auth'
    }
  }
});

// Function to create a temporary session for RLS context
export const setSupabaseAuth = async (privyUserId: string) => {
  console.log("[SUPABASE AUTH] ====== SETTING AUTH CONTEXT ======");
  console.log("[SUPABASE AUTH] privyUserId:", privyUserId);
  
  try {
    // Create a simple session that maps the Privy user ID to Supabase auth context
    const mockSession = {
      access_token: `privy-${privyUserId}`,
      refresh_token: `privy-refresh-${privyUserId}`,
      expires_in: 3600,
      token_type: 'bearer',
      user: {
        id: privyUserId,
        aud: 'authenticated',
        role: 'authenticated',
        email: '',
        app_metadata: {},
        user_metadata: {},
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      }
    };

    console.log("[SUPABASE AUTH] Setting session with access_token:", mockSession.access_token);
    
    // Set the session for RLS context
    const result = await supabase.auth.setSession({
      access_token: mockSession.access_token,
      refresh_token: mockSession.refresh_token
    });
    
    console.log("[SUPABASE AUTH] setSession result:", result);
    
    // Verify the session was set
    const { data: { session } } = await supabase.auth.getSession();
    console.log("[SUPABASE AUTH] Session verification:");
    console.log("[SUPABASE AUTH] - Session exists:", !!session);
    console.log("[SUPABASE AUTH] - Session user ID:", session?.user?.id);
    console.log("[SUPABASE AUTH] - Access token:", session?.access_token);
    
    if (session && session.user.id === privyUserId) {
      console.log("[SUPABASE AUTH] ✅ Auth context set successfully");
      return true;
    } else {
      console.error("[SUPABASE AUTH] ❌ Session verification failed");
      console.error("[SUPABASE AUTH] Expected user ID:", privyUserId);
      console.error("[SUPABASE AUTH] Actual user ID:", session?.user?.id);
      return false;
    }
  } catch (error) {
    console.error("[SUPABASE AUTH] ❌ Failed to set auth context:", error);
    console.error("[SUPABASE AUTH] Error details:", {
      message: error?.message,
      code: error?.code,
      details: error?.details
    });
    return false;
  }
};

// Helper function to clean up any auth state
export const clearAuthState = () => {
  console.log("[SUPABASE AUTH] ====== CLEARING AUTH STATE ======");
  
  // Clear any auth-related items from localStorage
  Object.keys(localStorage).forEach((key) => {
    if (key.startsWith('supabase.auth.') || key.includes('sb-')) {
      console.log("[SUPABASE AUTH] Removing localStorage key:", key);
      localStorage.removeItem(key);
    }
  });
  
  // Try to reset the auth session
  try {
    console.log("[SUPABASE AUTH] Signing out from Supabase");
    supabase.auth.signOut();
  } catch (error) {
    console.warn("[SUPABASE AUTH] Non-critical: Error during signout cleanup:", error);
  }
  
  console.log("[SUPABASE AUTH] ✅ Auth state cleared");
};

// Service for creating users securely via Edge Function
export const createUserSecurely = async (userData: {
  user_id: string;
  user_email: string;
  user_name?: string;
  user_role?: string;
}) => {
  try {
    console.log('[EDGE FUNCTION] ====== CALLING CREATE-USER ======');
    console.log('[EDGE FUNCTION] userData:', userData);
    
    const { data, error } = await supabase.functions.invoke('create-user', {
      body: userData
    });

    console.log('[EDGE FUNCTION] Raw response - data:', data);
    console.log('[EDGE FUNCTION] Raw response - error:', error);

    if (error) {
      console.error('[EDGE FUNCTION] ❌ Error calling create-user function:', error);
      throw new Error(`Failed to create user: ${error.message}`);
    }

    console.log('[EDGE FUNCTION] ✅ Create-user function response:', data);
    console.log('[EDGE FUNCTION] Returned user data:', data.data);
    return data.data;
  } catch (error) {
    console.error('[EDGE FUNCTION] ❌ Error in createUserSecurely:', error);
    throw error;
  }
};

// Service for creating groups securely via Edge Function
export const createGroupSecurely = async (groupData: {
  name: string;
  icon: string;
  created_by: string;
}) => {
  try {
    console.log('Calling create-group function with data:', groupData);
    
    const { data, error } = await supabase.functions.invoke('create-group', {
      body: groupData
    });

    if (error) {
      console.error('Error calling create-group function:', error);
      throw new Error(`Failed to create group: ${error.message}`);
    }

    console.log('Create-group function response:', data);
    return data.data;
  } catch (error) {
    console.error('Error in createGroupSecurely:', error);
    throw error;
  }
};

// Service for creating expenses securely via Edge Function
export const createExpenseSecurely = async (expenseData: {
  title: string;
  amount: number;
  currency: string;
  date: string;
  leftover_notes?: string;
  paid_by: string;
  group_id?: string;
  created_by: string;
}) => {
  try {
    console.log('Calling create-expense function with data:', expenseData);
    
    const { data, error } = await supabase.functions.invoke('create-expense', {
      body: expenseData
    });

    if (error) {
      console.error('Error calling create-expense function:', error);
      throw new Error(`Failed to create expense: ${error.message}`);
    }

    console.log('Create-expense function response:', data);
    return data.data;
  } catch (error) {
    console.error('Error in createExpenseSecurely:', error);
    throw error;
  }
};

// Service for verifying group membership via Edge Function (bypasses RLS)
export const verifyGroupMembership = async (groupId: string, userId: string) => {
  try {
    console.log('Verifying group membership via Edge Function:', { groupId, userId });
    
    const { data, error } = await supabase.functions.invoke('verify-group-membership', {
      body: { groupId, userId }
    });

    if (error) {
      console.error('Error calling verify-group-membership function:', error);
      throw new Error(`Failed to verify membership: ${error.message}`);
    }

    console.log('Raw Edge Function response:', data);

    // Safely extract the membership data from the response
    let membershipData;
    try {
      // The Edge Function returns { data: { isMember: boolean, role?: string } }
      if (data && typeof data === 'object') {
        if (data.data && typeof data.data === 'object') {
          membershipData = data.data;
        } else if (data.isMember !== undefined) {
          // Direct response format
          membershipData = data;
        } else {
          console.warn('Unexpected response structure:', data);
          throw new Error('Invalid response structure from membership verification');
        }
      } else {
        throw new Error('No data received from membership verification');
      }
    } catch (parseError) {
      console.error('Error parsing membership response:', parseError);
      throw new Error('Failed to parse membership verification response');
    }

    // Validate the response structure
    if (!membershipData || typeof membershipData.isMember !== 'boolean') {
      console.error('Invalid membership data structure:', membershipData);
      throw new Error('Invalid membership data received');
    }

    console.log('Parsed membership verification response:', membershipData);
    return membershipData;
    
  } catch (error) {
    console.error('Error in verifyGroupMembership:', error);
    throw error;
  }
};

// Service for fetching group data via Edge Function (bypasses RLS)
export const getGroupData = async (groupId: string, userId: string) => {
  try {
    console.log('Fetching group data via Edge Function:', { groupId, userId });
    
    const { data, error } = await supabase.functions.invoke('get-group-data', {
      body: { groupId, userId }
    });

    if (error) {
      console.error('Error calling get-group-data function:', error);
      throw new Error(`Failed to fetch group data: ${error.message}`);
    }

    console.log('Group data Edge Function response:', data);

    // Validate the response structure
    if (!data || !data.data) {
      throw new Error('Invalid group data response');
    }

    return {
      group: data.data,
      membership: data.membership
    };
    
  } catch (error) {
    console.error('Error in getGroupData:', error);
    throw error;
  }
};

// Simplified authenticated request wrapper
export const makeAuthenticatedRequest = async (privyUserId: string, requestFn: () => Promise<any>) => {
  try {
    console.log("[Request] 🚀 Making authenticated request for user:", privyUserId);
    
    // Set auth context and execute request
    const authSuccess = await setSupabaseAuth(privyUserId);
    if (!authSuccess) {
      throw new Error("Failed to set authentication context");
    }
    
    console.log("[Request] 📡 Executing request function...");
    const response = await requestFn();
    console.log("[Request] ✅ Request completed successfully");
    
    return response;
  } catch (error) {
    console.error('[Request] ❌ Error making authenticated request:', error);
    throw error;
  }
};
